/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Chapter = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'subjectName' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'subjectId' : IDL.Nat,
  'phone' : IDL.Text,
});
export const Subject = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'chapterCount' : IDL.Nat,
  'phone' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DeleteResult = IDL.Variant({
  'ok' : IDL.Null,
  'userNotFound' : IDL.Null,
});
export const AdminUserDetail = IDL.Record({
  'pin' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'details' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'details' : IDL.Text,
  'phone' : IDL.Text,
});
export const StudySession = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'subject' : IDL.Text,
  'endTime' : IDL.Int,
  'date' : IDL.Text,
  'durationSeconds' : IDL.Nat,
  'phone' : IDL.Text,
});
export const LoginResult = IDL.Variant({
  'ok' : UserProfile,
  'wrongPin' : IDL.Null,
  'userNotFound' : IDL.Null,
});
export const RegisterResult = IDL.Variant({
  'ok' : UserProfile,
  'invalidPhone' : IDL.Null,
  'invalidPin' : IDL.Null,
  'phoneAlreadyTaken' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addChapter' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : Chapter, 'err' : IDL.Text })],
      [],
    ),
  'addSubject' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Subject, 'err' : IDL.Text })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteChapter' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteStudySession' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'deleteSubject' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteUser' : IDL.Func([IDL.Text], [DeleteResult], []),
  'getAllUserDetails' : IDL.Func([], [IDL.Vec(AdminUserDetail)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChapters' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Vec(Chapter)], []),
  'getPendingChapters' : IDL.Func([IDL.Text], [IDL.Vec(Chapter)], []),
  'getPendingChaptersCount' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'getStudySessions' : IDL.Func([IDL.Text], [IDL.Vec(StudySession)], ['query']),
  'getSubjects' : IDL.Func([IDL.Text], [IDL.Vec(Subject)], []),
  'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginUser' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], ['query']),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [RegisterResult],
      [],
    ),
  'saveStudySession' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Int, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'updateChapterStatus' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Chapter = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'subjectName' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'subjectId' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const Subject = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'chapterCount' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DeleteResult = IDL.Variant({
    'ok' : IDL.Null,
    'userNotFound' : IDL.Null,
  });
  const AdminUserDetail = IDL.Record({
    'pin' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'details' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'details' : IDL.Text,
    'phone' : IDL.Text,
  });
  const StudySession = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'subject' : IDL.Text,
    'endTime' : IDL.Int,
    'date' : IDL.Text,
    'durationSeconds' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const LoginResult = IDL.Variant({
    'ok' : UserProfile,
    'wrongPin' : IDL.Null,
    'userNotFound' : IDL.Null,
  });
  const RegisterResult = IDL.Variant({
    'ok' : UserProfile,
    'invalidPhone' : IDL.Null,
    'invalidPin' : IDL.Null,
    'phoneAlreadyTaken' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addChapter' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : Chapter, 'err' : IDL.Text })],
        [],
      ),
    'addSubject' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Subject, 'err' : IDL.Text })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteChapter' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteStudySession' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'deleteSubject' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteUser' : IDL.Func([IDL.Text], [DeleteResult], []),
    'getAllUserDetails' : IDL.Func([], [IDL.Vec(AdminUserDetail)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChapters' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Vec(Chapter)], []),
    'getPendingChapters' : IDL.Func([IDL.Text], [IDL.Vec(Chapter)], []),
    'getPendingChaptersCount' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'getStudySessions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StudySession)],
        ['query'],
      ),
    'getSubjects' : IDL.Func([IDL.Text], [IDL.Vec(Subject)], []),
    'getUserProfile' : IDL.Func([IDL.Text], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginUser' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], ['query']),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [RegisterResult],
        [],
      ),
    'saveStudySession' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Int, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'updateChapterStatus' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };