/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminUserDetail {
  'pin' : string,
  'name' : string,
  'createdAt' : bigint,
  'details' : string,
  'phone' : string,
}
export type AttendanceResult = { 'ok' : GymAttendance } |
  { 'unauthorized' : null };
export type AttendanceStatus = { 'present' : null } |
  { 'rest' : null } |
  { 'absent' : null };
export interface Chapter {
  'id' : bigint,
  'status' : string,
  'subjectName' : string,
  'name' : string,
  'createdAt' : bigint,
  'subjectId' : bigint,
  'phone' : string,
}
export type DeleteResult = { 'ok' : null } |
  { 'userNotFound' : null };
export interface GymAttendance {
  'id' : string,
  'status' : AttendanceStatus,
  'date' : string,
  'note' : string,
  'phone' : string,
}
export type LoginResult = { 'ok' : UserProfile } |
  { 'wrongPin' : null } |
  { 'userNotFound' : null };
export interface Note {
  'id' : string,
  'title' : string,
  'content' : string,
  'subject' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'colorTag' : string,
  'phone' : string,
  'isPinned' : boolean,
}
export type NoteResult = { 'ok' : Note } |
  { 'notFound' : null } |
  { 'unauthorized' : null };
export interface Pdf {
  'id' : string,
  'subject' : string,
  'contentType' : string,
  'createdAt' : bigint,
  'fileData' : Uint8Array,
  'filename' : string,
  'phone' : string,
}
export type PdfResult = { 'ok' : Pdf } |
  { 'notFound' : null } |
  { 'unauthorized' : null };
export type RegisterResult = { 'ok' : UserProfile } |
  { 'invalidPhone' : null } |
  { 'invalidPin' : null } |
  { 'phoneAlreadyTaken' : null };
export interface StudySession {
  'id' : bigint,
  'startTime' : bigint,
  'subject' : string,
  'endTime' : bigint,
  'date' : string,
  'durationSeconds' : bigint,
  'phone' : string,
}
export interface Subject {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'chapterCount' : bigint,
  'phone' : string,
}
export interface UserProfile {
  'name' : string,
  'createdAt' : bigint,
  'details' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addChapter' : ActorMethod<
    [string, bigint, string],
    { 'ok' : Chapter } |
      { 'err' : string }
  >,
  'addNote' : ActorMethod<
    [string, string, string, string, string, boolean],
    NoteResult
  >,
  'addSubject' : ActorMethod<
    [string, string],
    { 'ok' : Subject } |
      { 'err' : string }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteChapter' : ActorMethod<
    [string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteNote' : ActorMethod<[string, string], boolean>,
  'deletePdf' : ActorMethod<[string, string], boolean>,
  'deleteStudySession' : ActorMethod<[string, bigint], boolean>,
  'deleteSubject' : ActorMethod<
    [string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteUser' : ActorMethod<[string], DeleteResult>,
  'getAllUserDetails' : ActorMethod<[], Array<AdminUserDetail>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getAppLogo' : ActorMethod<[], [] | [string]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChapters' : ActorMethod<[string, bigint], Array<Chapter>>,
  'getGymAttendance' : ActorMethod<[string], Array<GymAttendance>>,
  'getGymStreak' : ActorMethod<[string, string], bigint>,
  'getNotes' : ActorMethod<[string], Array<Note>>,
  'getPdfFile' : ActorMethod<[string], [] | [Uint8Array]>,
  'getPdfs' : ActorMethod<[string], Array<Pdf>>,
  'getPendingChapters' : ActorMethod<[string], Array<Chapter>>,
  'getPendingChaptersCount' : ActorMethod<[string], bigint>,
  'getStudySessions' : ActorMethod<[string], Array<StudySession>>,
  'getSubjects' : ActorMethod<[string], Array<Subject>>,
  'getUserProfile' : ActorMethod<[string], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginUser' : ActorMethod<[string, string], LoginResult>,
  'markGymAttendance' : ActorMethod<
    [string, string, AttendanceStatus, string],
    AttendanceResult
  >,
  'registerUser' : ActorMethod<
    [string, string, string, string],
    RegisterResult
  >,
  'saveStudySession' : ActorMethod<
    [string, string, bigint, string, bigint, bigint],
    bigint
  >,
  'setAppLogo' : ActorMethod<[string], undefined>,
  'toggleNotePin' : ActorMethod<[string, string], NoteResult>,
  'updateChapterStatus' : ActorMethod<
    [string, bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateNote' : ActorMethod<
    [string, string, string, string, string, string, boolean],
    NoteResult
  >,
  'uploadPdf' : ActorMethod<
    [string, string, string, Uint8Array, string],
    PdfResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];