/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AdminUserDetail {
    pin: string;
    name: string;
    createdAt: bigint;
    details: string;
    phone: string;
}
export type NoteResult = {
    __kind__: "ok";
    ok: Note;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
};
export type PdfResult = {
    __kind__: "ok";
    ok: Pdf;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
};
export type AttendanceResult = {
    __kind__: "ok";
    ok: GymAttendance;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
};
export interface Chapter {
    id: bigint;
    status: string;
    subjectName: string;
    name: string;
    createdAt: bigint;
    subjectId: bigint;
    phone: string;
}
export type RegisterResult = {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "invalidPhone";
    invalidPhone: null;
} | {
    __kind__: "invalidPin";
    invalidPin: null;
} | {
    __kind__: "phoneAlreadyTaken";
    phoneAlreadyTaken: null;
};
export interface GymAttendance {
    id: string;
    status: AttendanceStatus;
    date: string;
    note: string;
    phone: string;
}
export interface Pdf {
    id: string;
    subject: string;
    contentType: string;
    createdAt: bigint;
    fileData: Uint8Array;
    filename: string;
    phone: string;
}
export interface StudySession {
    id: bigint;
    startTime: bigint;
    subject: string;
    endTime: bigint;
    date: string;
    durationSeconds: bigint;
    phone: string;
}
export type LoginResult = {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "wrongPin";
    wrongPin: null;
} | {
    __kind__: "userNotFound";
    userNotFound: null;
};
export interface Subject {
    id: bigint;
    name: string;
    createdAt: bigint;
    chapterCount: bigint;
    phone: string;
}
export interface UserProfile {
    name: string;
    createdAt: bigint;
    details: string;
    phone: string;
}
export interface Note {
    id: string;
    title: string;
    content: string;
    subject: string;
    createdAt: bigint;
    updatedAt: bigint;
    colorTag: string;
    phone: string;
    isPinned: boolean;
}
export enum AttendanceStatus {
    present = "present",
    rest = "rest",
    absent = "absent"
}
export enum DeleteResult {
    ok = "ok",
    userNotFound = "userNotFound"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addChapter(phone: string, subjectId: bigint, name: string): Promise<{
        __kind__: "ok";
        ok: Chapter;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addNote(phone: string, subject: string, title: string, content: string, colorTag: string, isPinned: boolean): Promise<NoteResult>;
    addSubject(phone: string, name: string): Promise<{
        __kind__: "ok";
        ok: Subject;
    } | {
        __kind__: "err";
        err: string;
    }>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteChapter(phone: string, chapterId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteNote(phone: string, id: string): Promise<boolean>;
    deletePdf(phone: string, id: string): Promise<boolean>;
    deleteStudySession(phone: string, sessionId: bigint): Promise<boolean>;
    deleteSubject(phone: string, subjectId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteUser(phone: string): Promise<DeleteResult>;
    getAllUserDetails(): Promise<Array<AdminUserDetail>>;
    getAllUserProfiles(): Promise<Array<UserProfile>>;
    getAppLogo(): Promise<string | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChapters(phone: string, subjectId: bigint): Promise<Array<Chapter>>;
    getGymAttendance(phone: string): Promise<Array<GymAttendance>>;
    getGymStreak(phone: string, todayDate: string): Promise<bigint>;
    getNotes(phone: string): Promise<Array<Note>>;
    getPdfFile(id: string): Promise<Uint8Array | null>;
    getPdfs(phone: string): Promise<Array<Pdf>>;
    getPendingChapters(phone: string): Promise<Array<Chapter>>;
    getPendingChaptersCount(phone: string): Promise<bigint>;
    getStudySessions(phone: string): Promise<Array<StudySession>>;
    getSubjects(phone: string): Promise<Array<Subject>>;
    getUserProfile(phone: string): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    loginUser(phone: string, pin: string): Promise<LoginResult>;
    markGymAttendance(phone: string, date: string, status: AttendanceStatus, note: string): Promise<AttendanceResult>;
    registerUser(phone: string, name: string, details: string, pin: string): Promise<RegisterResult>;
    saveStudySession(phone: string, subject: string, durationSeconds: bigint, date: string, startTime: bigint, endTime: bigint): Promise<bigint>;
    setAppLogo(logo: string): Promise<void>;
    toggleNotePin(phone: string, id: string): Promise<NoteResult>;
    updateChapterStatus(phone: string, chapterId: bigint, status: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateNote(phone: string, id: string, subject: string, title: string, content: string, colorTag: string, isPinned: boolean): Promise<NoteResult>;
    uploadPdf(phone: string, subject: string, filename: string, fileData: Uint8Array, contentType: string): Promise<PdfResult>;
}
import type { AttendanceResult as _AttendanceResult, AttendanceStatus as _AttendanceStatus, Chapter as _Chapter, DeleteResult as _DeleteResult, GymAttendance as _GymAttendance, LoginResult as _LoginResult, Note as _Note, NoteResult as _NoteResult, Pdf as _Pdf, PdfResult as _PdfResult, RegisterResult as _RegisterResult, Subject as _Subject, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addChapter(arg0: string, arg1: bigint, arg2: string): Promise<{
        __kind__: "ok";
        ok: Chapter;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addChapter(arg0, arg1, arg2);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChapter(arg0, arg1, arg2);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addNote(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: boolean): Promise<NoteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addNote(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_NoteResult_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNote(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_NoteResult_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async addSubject(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: Subject;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addSubject(arg0, arg1);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSubject(arg0, arg1);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteChapter(arg0: string, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteChapter(arg0, arg1);
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteChapter(arg0, arg1);
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteNote(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0, arg1);
            return result;
        }
    }
    async deletePdf(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePdf(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePdf(arg0, arg1);
            return result;
        }
    }
    async deleteStudySession(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudySession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudySession(arg0, arg1);
            return result;
        }
    }
    async deleteSubject(arg0: string, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubject(arg0, arg1);
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubject(arg0, arg1);
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteUser(arg0: string): Promise<DeleteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return from_candid_DeleteResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return from_candid_DeleteResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserDetails(): Promise<Array<AdminUserDetail>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserDetails();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserDetails();
            return result;
        }
    }
    async getAllUserProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return result;
        }
    }
    async getAppLogo(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppLogo();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppLogo();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChapters(arg0: string, arg1: bigint): Promise<Array<Chapter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChapters(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChapters(arg0, arg1);
            return result;
        }
    }
    async getGymAttendance(arg0: string): Promise<Array<GymAttendance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGymAttendance(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGymAttendance(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGymStreak(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getGymStreak(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGymStreak(arg0, arg1);
            return result;
        }
    }
    async getNotes(arg0: string): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotes(arg0);
            return result;
        }
    }
    async getPdfFile(arg0: string): Promise<Uint8Array | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPdfFile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPdfFile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPdfs(arg0: string): Promise<Array<Pdf>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPdfs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPdfs(arg0);
            return result;
        }
    }
    async getPendingChapters(arg0: string): Promise<Array<Chapter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingChapters(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingChapters(arg0);
            return result;
        }
    }
    async getPendingChaptersCount(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingChaptersCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingChaptersCount(arg0);
            return result;
        }
    }
    async getStudySessions(arg0: string): Promise<Array<StudySession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudySessions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudySessions(arg0);
            return result;
        }
    }
    async getSubjects(arg0: string): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjects(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjects(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async loginUser(arg0: string, arg1: string): Promise<LoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.loginUser(arg0, arg1);
                return from_candid_LoginResult_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginUser(arg0, arg1);
            return from_candid_LoginResult_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async markGymAttendance(arg0: string, arg1: string, arg2: AttendanceStatus, arg3: string): Promise<AttendanceResult> {
        if (this.processError) {
            try {
                const result = await this.actor.markGymAttendance(arg0, arg1, to_candid_AttendanceStatus_n22(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_AttendanceResult_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markGymAttendance(arg0, arg1, to_candid_AttendanceStatus_n22(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_AttendanceResult_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string, arg3: string): Promise<RegisterResult> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2, arg3);
                return from_candid_RegisterResult_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2, arg3);
            return from_candid_RegisterResult_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveStudySession(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: bigint, arg5: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveStudySession(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveStudySession(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async setAppLogo(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAppLogo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAppLogo(arg0);
            return result;
        }
    }
    async toggleNotePin(arg0: string, arg1: string): Promise<NoteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleNotePin(arg0, arg1);
                return from_candid_NoteResult_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleNotePin(arg0, arg1);
            return from_candid_NoteResult_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateChapterStatus(arg0: string, arg1: bigint, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateChapterStatus(arg0, arg1, arg2);
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateChapterStatus(arg0, arg1, arg2);
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateNote(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: boolean): Promise<NoteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNote(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_NoteResult_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNote(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_NoteResult_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async uploadPdf(arg0: string, arg1: string, arg2: string, arg3: Uint8Array, arg4: string): Promise<PdfResult> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPdf(arg0, arg1, arg2, arg3, arg4);
                return from_candid_PdfResult_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPdf(arg0, arg1, arg2, arg3, arg4);
            return from_candid_PdfResult_n28(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AttendanceResult_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceResult): AttendanceResult {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceStatus): AttendanceStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_DeleteResult_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeleteResult): DeleteResult {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_GymAttendance_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GymAttendance): GymAttendance {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_LoginResult_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginResult): LoginResult {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_NoteResult_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NoteResult): NoteResult {
    return from_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function from_candid_PdfResult_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PdfResult): PdfResult {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_RegisterResult_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegisterResult): RegisterResult {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _AttendanceStatus;
    date: string;
    note: string;
    phone: string;
}): {
    id: string;
    status: AttendanceStatus;
    date: string;
    note: string;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_AttendanceStatus_n16(_uploadFile, _downloadFile, value.status),
        date: value.date,
        note: value.note,
        phone: value.phone
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Chapter;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Chapter;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    present: null;
} | {
    rest: null;
} | {
    absent: null;
}): AttendanceStatus {
    return "present" in value ? AttendanceStatus.present : "rest" in value ? AttendanceStatus.rest : "absent" in value ? AttendanceStatus.absent : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    wrongPin: null;
} | {
    userNotFound: null;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "wrongPin";
    wrongPin: null;
} | {
    __kind__: "userNotFound";
    userNotFound: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "wrongPin" in value ? {
        __kind__: "wrongPin",
        wrongPin: value.wrongPin
    } : "userNotFound" in value ? {
        __kind__: "userNotFound",
        userNotFound: value.userNotFound
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _GymAttendance;
} | {
    unauthorized: null;
}): {
    __kind__: "ok";
    ok: GymAttendance;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_GymAttendance_n14(_uploadFile, _downloadFile, value.ok)
    } : "unauthorized" in value ? {
        __kind__: "unauthorized",
        unauthorized: value.unauthorized
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    invalidPhone: null;
} | {
    invalidPin: null;
} | {
    phoneAlreadyTaken: null;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "invalidPhone";
    invalidPhone: null;
} | {
    __kind__: "invalidPin";
    invalidPin: null;
} | {
    __kind__: "phoneAlreadyTaken";
    phoneAlreadyTaken: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "invalidPhone" in value ? {
        __kind__: "invalidPhone",
        invalidPhone: value.invalidPhone
    } : "invalidPin" in value ? {
        __kind__: "invalidPin",
        invalidPin: value.invalidPin
    } : "phoneAlreadyTaken" in value ? {
        __kind__: "phoneAlreadyTaken",
        phoneAlreadyTaken: value.phoneAlreadyTaken
    } : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Pdf;
} | {
    notFound: null;
} | {
    unauthorized: null;
}): {
    __kind__: "ok";
    ok: Pdf;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "unauthorized" in value ? {
        __kind__: "unauthorized",
        unauthorized: value.unauthorized
    } : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Note;
} | {
    notFound: null;
} | {
    unauthorized: null;
}): {
    __kind__: "ok";
    ok: Note;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "unauthorized" in value ? {
        __kind__: "unauthorized",
        unauthorized: value.unauthorized
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Subject;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Subject;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    userNotFound: null;
}): DeleteResult {
    return "ok" in value ? DeleteResult.ok : "userNotFound" in value ? DeleteResult.userNotFound : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GymAttendance>): Array<GymAttendance> {
    return value.map((x)=>from_candid_GymAttendance_n14(_uploadFile, _downloadFile, x));
}
function to_candid_AttendanceStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): _AttendanceStatus {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): {
    present: null;
} | {
    rest: null;
} | {
    absent: null;
} {
    return value == AttendanceStatus.present ? {
        present: null
    } : value == AttendanceStatus.rest ? {
        rest: null
    } : value == AttendanceStatus.absent ? {
        absent: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
